// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE9U1w55JOEGkt5tgW1DKTDQjzbZjwww8',
    appId: '1:370916634918:web:aa831ef4bef31a696bd1e7',
    messagingSenderId: '370916634918',
    projectId: 'fridayproj-2fa23',
    authDomain: 'fridayproj-2fa23.firebaseapp.com',
    storageBucket: 'fridayproj-2fa23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-tK4Wuu8l5lR8zOb5Sk6oGmFq6RHq9n0',
    appId: '1:370916634918:android:b3a64c3ae3f6a5e56bd1e7',
    messagingSenderId: '370916634918',
    projectId: 'fridayproj-2fa23',
    storageBucket: 'fridayproj-2fa23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR_RSB-A-35fQESxsb_yaCabbMKxz21u8',
    appId: '1:370916634918:ios:dc4127942c765b3d6bd1e7',
    messagingSenderId: '370916634918',
    projectId: 'fridayproj-2fa23',
    storageBucket: 'fridayproj-2fa23.appspot.com',
    iosBundleId: 'com.example.firestoreDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR_RSB-A-35fQESxsb_yaCabbMKxz21u8',
    appId: '1:370916634918:ios:29faa6fc03732dcd6bd1e7',
    messagingSenderId: '370916634918',
    projectId: 'fridayproj-2fa23',
    storageBucket: 'fridayproj-2fa23.appspot.com',
    iosBundleId: 'com.example.firestoreDemo.RunnerTests',
  );
}
